name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Project relative
      run: |
        npm install
        npm run test
        npm run docz:build
